service: notes-api

frameworkVersion: "3"
useDotenv: true

provider:

  name: aws
  runtime: nodejs18.x
  profile: ${env:AWS_PROFILE}
  region: eu-north-1
  iam:
    role: arn:aws:iam::213613991334:role/notes
  lambdaHashingVersion: 20201221
  

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  createNote:
    handler: functions/createNote/index.handler
    events:
      - httpApi:
          path: /api/notes
          method: POST
  getNotes:
    handler: functions/getNotes/index.handler
    events:
      - httpApi:
          path: /api/notes
          method: GET
  changeNote:
    handler: functions/changeNote/index.handler
    events:
      - httpApi:
          path: /api/notes
          method: PUT
  deleteNote:
    handler: functions/deleteNote/index.handler
    events:
      - httpApi:
          path: /api/notes
          method: DELETE
  signup:
    handler: functions/signup/index.handler
    events:
      - httpApi:
          path: /api/user/signup
          method: POST
  login:
    handler: functions/login/index.handler
    events:
      - httpApi:
          path: /api/user/login
          method: POST

resources:
  Resources:
    UserNotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserNotes
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
